# The name of your Worker in the Cloudflare dashboard.
name = "rapid-scene-1da6"

# The main entrypoint for your Worker script.
main = "worker.js"

# The compatibility date specifies which version of the Workers runtime is used.
compatibility_date = "2024-03-20"

# Enables Node.js compatibility APIs, required for features like TCP sockets (`connect`).
compatibility_flags = ["nodejs_compat"]
