name = "rapid-scene-1da6"
main = "worker.js"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "v2v_kv"
id = "a71ebd79ab2e4c3883e1303e16141537" # ✅ این ID باید دقیقاً با ID KV Namespace شما مطابقت داشته باشد.
