name = "rapid-scene-1da6"
main = "worker.js"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "V2V_KV"
id = "a71ebd79ab2e4c3883e1303e16141537"

# --- Set Environment Variables in Cloudflare Dashboard ---
# [vars]
# PRIMARY_CONFIGS_URL = "https://your-primary-source.com/all_live_configs.json"
# FALLBACK_CONFIGS_URL = "https://your-fallback-source.com/all_live_configs.json"
