# نام Worker شما در داشبورد کلادفلر
name = "rapid-scene-1da6"

# فایل اصلی کد شما
main = "worker.js"

# تاریخ سازگاری برای استفاده از قابلیت‌های جدید
compatibility_date = "2024-03-20"

# فعال‌سازی سازگاری با Node.js (برای تست پینگ از سمت سرور)
compatibility_flags = ["nodejs_compat"]

# اتصال به انبار کلید-مقدار (KV Namespace)
# اینجا ورکر به دیتابیس شما متصل می‌شود
[[kv_namespaces]]
binding = "V2V_KV"
id = "a71ebd79ab2e4c3883e1303e16141537"
